/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "GetRightData Docs",
  "tagline": "Unified customer trust, insight, and data exchange documentation",
  "url": "https://docs.getrightdata.com",
  "baseUrl": "/",
  "favicon": "img/logo-light.svg",
  "organizationName": "GetRightData",
  "projectName": "docs-platform",
  "onBrokenLinks": "throw",
  "trailingSlash": false,
  "deploymentBranch": "gh-pages",
  "headTags": [
    {
      "tagName": "link",
      "attributes": {
        "rel": "preconnect",
        "href": "https://fonts.gstatic.com",
        "crossOrigin": "anonymous"
      }
    }
  ],
  "customFields": {
    "legacyZendeskBaseUrl": "https://getrightdata.zendesk.com/hc/en-us",
    "askPageUrl": "https://getrightdata.com/contact",
    "rawContentBaseUrl": "https://raw.githubusercontent.com/GetRightData/docs/main/",
    "localeOptions": {
      "regions": [
        {
          "code": "us",
          "label": "United States"
        },
        {
          "code": "eu",
          "label": "Europe"
        }
      ],
      "languages": [
        {
          "code": "en",
          "label": "English (United States)"
        },
        {
          "code": "en-gb",
          "label": "English (United Kingdom)"
        }
      ],
      "defaultRegion": "us",
      "defaultLanguage": "en"
    },
    "organizations": [
      {
        "id": "getrightdata",
        "slug": "getrightdata",
        "displayName": "GetRightData",
        "defaultProduct": "datatrust",
        "theme": {
          "logoLight": "img/logos/grd-light.svg",
          "logoDark": "img/logos/grd-dark.svg",
          "primary": "#4338CA",
          "secondary": "#6366F1"
        },
        "products": [
          "datatrust",
          "rightsight",
          "datamarket",
          "api",
          "release-notes"
        ]
      }
    ],
    "products": [
      {
        "id": "datatrust",
        "displayName": "DataTrust",
        "slug": "datatrust",
        "entryDoc": "getting-started",
        "versioning": {
          "type": "versioned",
          "current": "7.6",
          "archived": [
            "7.0"
          ],
          "label": "7.6"
        }
      },
      {
        "id": "rightsight",
        "displayName": "RightSight",
        "slug": "rightsight",
        "entryDoc": "overview",
        "versioning": {
          "type": "latest",
          "label": "Latest"
        }
      },
      {
        "id": "datamarket",
        "displayName": "DataMarket",
        "slug": "datamarket",
        "entryDoc": "overview",
        "versioning": {
          "type": "latest",
          "label": "Latest"
        }
      },
      {
        "id": "api",
        "displayName": "API Reference",
        "slug": "api",
        "entryDoc": "authentication",
        "versioning": {
          "type": "latest",
          "label": "Latest"
        }
      },
      {
        "id": "release-notes",
        "displayName": "Release Notes",
        "slug": "release-notes",
        "entryDoc": "7-6",
        "versioning": {
          "type": "latest",
          "label": "Latest"
        }
      }
    ],
    "defaultOrgId": "getrightdata"
  },
  "themes": [],
  "presets": [
    [
      "classic",
      {
        "docs": false,
        "blog": false,
        "theme": {
          "customCss": "/Users/anilpulugujja/Documents/Projects/Active/DocumentationProject/documentation/docs-platform/src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "getrightdata-datatrust",
        "path": "organizations/getrightdata/products/datatrust/docs",
        "routeBasePath": "getrightdata/datatrust",
        "sidebarPath": "/Users/anilpulugujja/Documents/Projects/Active/DocumentationProject/documentation/docs-platform/organizations/getrightdata/products/datatrust/sidebar.js",
        "editUrl": "https://github.com/GetRightData/docs/edit/main/organizations/getrightdata/products/datatrust/docs/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "includeCurrentVersion": true,
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "7.6",
            "path": "7.6"
          },
          "7.0": {
            "label": "7.0 (Archived)",
            "path": "7.0",
            "banner": "unmaintained"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "getrightdata-rightsight",
        "path": "organizations/getrightdata/products/rightsight/docs",
        "routeBasePath": "getrightdata/rightsight",
        "sidebarPath": "/Users/anilpulugujja/Documents/Projects/Active/DocumentationProject/documentation/docs-platform/organizations/getrightdata/products/rightsight/sidebar.js",
        "editUrl": "https://github.com/GetRightData/docs/edit/main/organizations/getrightdata/products/rightsight/docs/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "includeCurrentVersion": true,
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "Latest",
            "path": "latest"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "getrightdata-datamarket",
        "path": "organizations/getrightdata/products/datamarket/docs",
        "routeBasePath": "getrightdata/datamarket",
        "sidebarPath": "/Users/anilpulugujja/Documents/Projects/Active/DocumentationProject/documentation/docs-platform/organizations/getrightdata/products/datamarket/sidebar.js",
        "editUrl": "https://github.com/GetRightData/docs/edit/main/organizations/getrightdata/products/datamarket/docs/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "includeCurrentVersion": true,
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "Latest",
            "path": "latest"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "getrightdata-api",
        "path": "organizations/getrightdata/products/api/docs",
        "routeBasePath": "getrightdata/api",
        "sidebarPath": "/Users/anilpulugujja/Documents/Projects/Active/DocumentationProject/documentation/docs-platform/organizations/getrightdata/products/api/sidebar.js",
        "editUrl": "https://github.com/GetRightData/docs/edit/main/organizations/getrightdata/products/api/docs/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "includeCurrentVersion": true,
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "Latest",
            "path": "latest"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "getrightdata-release-notes",
        "path": "organizations/getrightdata/products/release-notes/docs",
        "routeBasePath": "getrightdata/release-notes",
        "sidebarPath": "/Users/anilpulugujja/Documents/Projects/Active/DocumentationProject/documentation/docs-platform/organizations/getrightdata/products/release-notes/sidebar.js",
        "editUrl": "https://github.com/GetRightData/docs/edit/main/organizations/getrightdata/products/release-notes/docs/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "includeCurrentVersion": true,
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "Latest",
            "path": "latest"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {}
    ]
  ],
  "themeConfig": {
    "image": "img/social-card.png",
    "breadcrumbs": {
      "barStyle": "default"
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "DataTrust, RightSight, DataMarket, governance, monitoring"
      },
      {
        "name": "theme-color",
        "content": "#1d2cf3"
      }
    ],
    "navbar": {
      "title": "GetRightData",
      "logo": {
        "alt": "GetRightData logo",
        "src": "img/logo-light.svg",
        "srcDark": "img/logo-dark.svg"
      },
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "docsPluginId": "getrightdata-datatrust",
          "sidebarId": "datatrustSidebar",
          "label": "DataTrust",
          "to": "/getrightdata/datatrust/7.6/getting-started",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "docsPluginId": "getrightdata-rightsight",
          "sidebarId": "rightsightSidebar",
          "label": "RightSight",
          "to": "/getrightdata/rightsight/latest/overview",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "docsPluginId": "getrightdata-datamarket",
          "sidebarId": "datamarketSidebar",
          "label": "DataMarket",
          "to": "/getrightdata/datamarket/latest/overview",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "docsPluginId": "getrightdata-api",
          "sidebarId": "apiSidebar",
          "label": "API",
          "to": "/getrightdata/api/latest/authentication",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "docsPluginId": "getrightdata-release-notes",
          "sidebarId": "releaseNotesSidebar",
          "label": "Release Notes",
          "to": "/getrightdata/release-notes/latest/7-6",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "docsPluginId": "getrightdata-datatrust",
          "position": "right",
          "dropdownItemsAfter": [
            {
              "to": "https://getrightdata.com",
              "label": "getrightdata.com"
            }
          ],
          "dropdownItemsBefore": []
        },
        {
          "href": "https://getrightdata.com",
          "label": "Main Site",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Products",
          "items": [
            {
              "label": "DataTrust",
              "to": "/getrightdata/datatrust/7.6/getting-started"
            },
            {
              "label": "RightSight",
              "to": "/getrightdata/rightsight/latest/overview"
            },
            {
              "label": "DataMarket",
              "to": "/getrightdata/datamarket/latest/overview"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "API Reference",
              "to": "/getrightdata/api/latest/authentication"
            },
            {
              "label": "Release Notes",
              "to": "/getrightdata/release-notes/latest/7-6"
            },
            {
              "label": "Status",
              "href": "https://status.getrightdata.com"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "getrightdata.com",
              "href": "https://getrightdata.com"
            },
            {
              "label": "Support",
              "href": "mailto:support@getrightdata.com"
            },
            {
              "label": "Privacy",
              "href": "https://getrightdata.com/privacy"
            }
          ]
        }
      ],
      "copyright": "© 2026 GetRightData. All rights reserved."
    },
    "colorMode": {
      "defaultMode": "light",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "powershell",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
